local httpd = require("dooing.sync.httpd")

describe("httpd parser", function()
	it("parses a simple GET in one chunk", function()
		local parser = httpd.new_parser()
		local request = parser:feed("GET /todos HTTP/1.1\r\nHost: 192.168.1.2:7283\r\n\r\n")
		truthy(request)
		eq(request.method, "GET")
		eq(request.path, "/todos")
		eq(request.headers.host, "192.168.1.2:7283")
		eq(request.body, "")
	end)

	it("strips the query string into its own field", function()
		local parser = httpd.new_parser()
		local request = parser:feed("GET /todos?x=1 HTTP/1.1\r\n\r\n")
		eq(request.path, "/todos")
		eq(request.query, "x=1")
	end)

	it("lower-cases header names", function()
		local parser = httpd.new_parser()
		local request = parser:feed("GET / HTTP/1.1\r\nAuthorization: Bearer abc\r\n\r\n")
		eq(request.headers.authorization, "Bearer abc")
	end)

	it("waits for the full head across chunks", function()
		local parser = httpd.new_parser()
		eq(parser:feed("GET /todos HT"), nil)
		eq(parser:feed("TP/1.1\r\nHost: 10.0.0.1"), nil)
		local request = parser:feed(":7283\r\n\r\n")
		truthy(request)
		eq(request.headers.host, "10.0.0.1:7283")
	end)

	it("waits for the full body across chunks", function()
		local parser = httpd.new_parser()
		eq(parser:feed('POST /v2/pair HTTP/1.1\r\nContent-Length: 11\r\n\r\n{"a"'), nil)
		local request = parser:feed(':"bcd"}')
		truthy(request)
		eq(request.body, '{"a":"bcd"}')
	end)

	it("handles a body that arrives with the head", function()
		local parser = httpd.new_parser()
		local request = parser:feed("POST /v2/pair HTTP/1.1\r\nContent-Length: 2\r\n\r\nok")
		truthy(request)
		eq(request.body, "ok")
	end)

	it("rejects a malformed request line", function()
		local parser = httpd.new_parser()
		local request, err = parser:feed("NOT A REQUEST\r\n\r\n")
		eq(request, nil)
		truthy(err)
	end)

	it("rejects oversized headers", function()
		local parser = httpd.new_parser()
		local request, err = parser:feed("GET / HTTP/1.1\r\nX-Junk: " .. ("a"):rep(httpd.MAX_HEADER_BYTES + 1))
		eq(request, nil)
		eq(err, "headers too large")
	end)

	it("rejects oversized bodies before reading them", function()
		local parser = httpd.new_parser()
		local request, err =
			parser:feed(("POST /v2/pair HTTP/1.1\r\nContent-Length: %d\r\n\r\n"):format(httpd.MAX_BODY_BYTES + 1))
		eq(request, nil)
		eq(err, "body too large")
	end)

	it("rejects chunked transfer encoding", function()
		local parser = httpd.new_parser()
		local request, err = parser:feed("POST / HTTP/1.1\r\nTransfer-Encoding: chunked\r\n\r\n")
		eq(request, nil)
		eq(err, "unsupported framing")
	end)
end)

describe("httpd guards", function()
	it("accepts an IPv4 Host with the right port", function()
		truthy(httpd.check_host("192.168.1.2:7283", 7283))
	end)

	it("accepts localhost", function()
		truthy(httpd.check_host("localhost:7283", 7283))
	end)

	it("rejects a DNS name — the rebinding vector", function()
		falsy(httpd.check_host("evil.example.com:7283", 7283))
	end)

	it("rejects the wrong port", function()
		falsy(httpd.check_host("192.168.1.2:9999", 7283))
	end)

	it("rejects a missing Host", function()
		falsy(httpd.check_host(nil, 7283))
	end)

	it("rejects an out-of-range IPv4", function()
		falsy(httpd.check_host("192.168.1.300:7283", 7283))
	end)

	it("accepts a bracketed IPv6 literal", function()
		truthy(httpd.check_host("[fe80::1]:7283", 7283))
	end)

	it("rejects any request carrying Origin", function()
		truthy(httpd.check_origin(nil))
		falsy(httpd.check_origin("http://evil.example.com"))
		falsy(httpd.check_origin("null"))
	end)
end)

describe("httpd responses", function()
	it("never emits Access-Control-Allow-Origin", function()
		local response = httpd.response(200, "application/json", "[]")
		falsy(response:lower():find("access-control", 1, true))
	end)

	it("carries an accurate Content-Length", function()
		local response = httpd.response(200, "text/plain", "hello")
		truthy(response:find("Content-Length: 5\r\n", 1, true))
	end)
end)
